const { GoogleGenAI } = require('@google/genai')
const z = require('zod')
const {zodToJsonSchema} = require('zod-to-json-schema')
const puppeteer = require('puppeteer');



const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
})

const interviewReportSchema = z.object({
    matchScore: z.number().describe("A score between 0 and 100 indicating how well the candidate's resume and self-description match the job description."),
    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical question can be asked during the interview"),
        intention: z.string().describe("The intention of interviewerbehind asking the question"),
        answer: z.string().describe("How to answer the question, what points to cover, what approach to take, etc.")
    })).describe("Technical questions that can be asked during the interview along with the intention behind asking them and how to answer them."),

    behavioralQuestions: z.array(z.object({
        question: z.string().describe("The behavioral question can be asked during the interview"),
        intention: z.string().describe("The intention of interviewer behind asking the question"),
        answer: z.string().describe("How to answer the question, what points to cover, what approach to take, etc.")
    })).describe("Behavioral questions that can be asked during the interview along with the intention behind asking them and how to answer them."),

    skillGaps: z.array(z.object({
        skill: z.string().describe("The skill that the candidate is lacking"),
        severity: z.enum(["low", "medium", "high"]).describe("The severity of the skill gap"),
    })).describe("List of skill gaps that the candidate has along with the severity."),

    preperationPlan: z.array(z.object({
        day: z.number().describe("The day number in the preparation plan, starting from 1"),
        focus: z.string().describe("The main focus of the day in the preparation plan, e.g., 'Data Structures and Algorithms', 'System Design', 'mock interviews', etc."),
        tasks: z.array(z.string()).describe("The list of tasks to be done on that day in the preparation plan, e.g., read a specific book chapter, solve a set of problems, watch a specific video, etc.")
    })).describe("A day wise preparation plan for the candidate to follow in order to improve their chances of success in the interview."),
    title: z.string().describe("The title of the job for which the interview report is generated"),


})

async function generateInterviewReport({resume, selfDescription, jobDescription}) {

    const prompt = `Generate an interview report for a candidate based on the following information:
                    Resume: ${resume}
                    Self Description: ${selfDescription}
                    Job Description: ${jobDescription}`

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
            responseMimeType: 'application/json',
            responseSchema: zodToJsonSchema(interviewReportSchema)
        },

    })

    

    return JSON.parse(response.text);
}

async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch({
  headless: true,
  args: [
    "--no-sandbox",
    "--disable-setuid-sandbox"
  ]
});
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    const pdfBuffer = await page.pdf({ format: 'A4', margin: {
        top: '20mm',
        bottom: '20mm',
        left: '15mm',
        right: '15mm'
    } 
});

    await browser.close();

    return pdfBuffer;
}


async function generateResumePdf({resume, selfDescription, jobDescription}) {

    const resumepdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer"),
    })

    const prompt = `Generate resume for a candidate with the following information:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        The response should be in JSON format with a single field "html" which can be converted into PDF using any library like puppeteer
                        The resume should be tailored to the job description and should highlight the candidate's skills and experience that are relevant to the job. The resume should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of the resume should not sound like its generated by AI and should be close as possible to a real human written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should be ideally be 1-2 A4 pages long when converted to PDF. Focus on Quality rather than quantity and make sure to include all relevant information that can increase the candidate's chances of getting the interview call for the given job description.
                    `
    
    const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: prompt,
        config: {
            responseMimeType: 'application/json',
            responseSchema: zodToJsonSchema(resumepdfSchema)
        }
        
    })


    const jsonContent =  JSON.parse(response.text);

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html);


    return pdfBuffer;
}


module.exports = { generateInterviewReport, generateResumePdf };
